name: Contentful CI/CD Env Migration 

on:
  workflow_dispatch:
    inputs:
      brand:
        description: 'Select brand (Contentful space) to deploy'
        required: true
        type: choice
        options:
          - Dev R&D
          - Fitness First
          - Goodlife Website
          - Gym Website
          - Jetts New Zealand
          - Zap Fitness
    workflows: ["Contentful CI/CD Env Locking"]
    types:
      - completed

env:
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
  MASTER_ALIAS: master
  NODE_VERSION: 18

jobs:
  # Production Promotion: Promote/Unlock env
  migrate-contentful:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Contentful CLI
        run: npm install -g contentful-cli contentful-migration contentful-merge
      
      - name: Set SPACE_ID based on brand input
        id: set_space
        run: |
          case "${{ github.event.inputs.brand }}" in
            "Fitness First")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_FITNESS_FIRST }}" >> $GITHUB_ENV
              ;;
            "Dev R&D")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}" >> $GITHUB_ENV
              ;;
            "Goodlife Website")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_GOODLIFE_WEBSITE }}" >> $GITHUB_ENV
              ;;
            "Gym Website")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_GYM_WEBSITE }}" >> $GITHUB_ENV
              ;;
            "Jetts New Zealand")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_JETTS_NEW_ZEALAND }}" >> $GITHUB_ENV
              ;;
            "Zap Fitness")
              echo "SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_ZAP_FITNESS }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown brand '${{ github.event.inputs.brand }}'"
              exit 1
              ;;
          esac
      
      - name: Fetch latest environment version
        id: fetch_env
        run: |
          echo "Fetching environments for SPACE_ID=$SPACE_ID"

          # Fetch env list from Contentful API
          curl -s \
            -H "Authorization: Bearer $CONTENTFUL_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.contentful.com/spaces/$SPACE_ID/environments" \
            > envs_raw.json

          # Find highest version like master-vN
          latest_env=$(jq -r '[.items[] | select(.name | test("^master-v[0-9]+$")) 
                              | .name 
                              | capture("master-v(?<num>[0-9]+)").num | tonumber] 
                              | max' envs_raw.json)

          if [ "$latest_env" = "null" ]; then
            echo "No versioned env found, defaulting to master"
            target_env="master"
          else
            target_env="master-v${latest_env}"
          fi

          echo "TARGET_ENV=$target_env" >> $GITHUB_ENV
          echo "Resolved TARGET_ENV=$target_env"

      - name: Update master alias
        run: |
          contentful space environment-alias update \
            --space-id "$SPACE_ID" \
            --alias-id "$MASTER_ALIAS" \
            --target-environment-id "$TARGET_ENV" \
            --management-token "$CONTENTFUL_TOKEN"
        env:
          SPACE_ID: ${{ env.SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          MASTER_ALIAS: ${{ env.MASTER_ALIAS }}
          TARGET_ENV: ${{ env.TARGET_ENV }}

      - name: Download roles backup artifact
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: contentful-roles-backup
          path: ./rollback

      - name: Unlock master environment
        if: always()
        run: bash ./scripts/contentful-unlock-master.sh "$SPACE_ID" "$CONTENTFUL_TOKEN"
        env:
          SPACE_ID: ${{ env.SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
        