name: Contentful CI/CD

on:
  workflow_dispatch:

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
  NODE_VERSION: 18

jobs:
  # Production Promotion: Lock/Promote/Unlock
  migrate-contentful:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Contentful CLI
        run: npm install -g contentful-cli
      
      - name: Clone environments
        run: |
          contentful space environment create \
            --space-id "$CONTENTFUL_SPACE_ID" \
            --management-token "$CONTENTFUL_TOKEN" \
            --environment-id testing1 \
            --source-environment master
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}

      # # Run ALL migration scripts in cloned environment using the GitHub Action  
      # - name: Run migration scripts
      #   uses: contentful-userland/contentful-action@main
      #   with:
      #     space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
      #     management_api_key: ${{ secrets.CONTENTFUL_TOKEN }}
      #     migrations_dir: migrations
      #     environment_id: NEW_ENV
      
      #Run a specific migration script
      - name: Run specific migration script in cloned environment
        run: |
          contentful-migration \
            --space-id "$CONTENTFUL_SPACE_ID" \
            --management-token "$CONTENTFUL_MANAGEMENT_TOKEN" \
            --environment-id testing1 \
            Migrations/index.js
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
      
      - name: Lock master environment
        run: bash ./scripts/contentful-lock-master.sh "$CONTENTFUL_SPACE_ID" "$CONTENTFUL_TOKEN"
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}

      - name: Upload roles backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: contentful-roles-backup
          path: roles-backup.json
          retention-days: 1

      - name: Update master alias
        run: |
          contentful space environment-alias update \
            --space-id "$CONTENTFUL_SPACE_ID" \
            --alias-id master \
            --target-environment-id testing1 \
            --management-token "$CONTENTFUL_TOKEN"
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}

      - name: Download roles backup artifact
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: contentful-roles-backup
          path: .

      - name: Unlock master environment
        if: always()
        run: bash ./scripts/contentful-unlock-master.sh "$CONTENTFUL_SPACE_ID" "$CONTENTFUL_TOKEN"
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
        