name: Contentful CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      source_env:
        description: "Source environment (for manual merge)"
        required: true
        default: master
      target_env:
        description: "Target environment (for manual merge)"
        required: true
        default: staging

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
  CONTENTFUL_CDA_TOKEN: ${{ secrets.CONTENTFUL_CDA_TOKEN }}
  NODE_VERSION: 18

jobs:
  # Preview env handler
  preview-env:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Contentful CLI
        run: npm install -g contentful-cli
      - name: Create preview environment
        run: |
          contentful environment create \
            --space-id ${{ env.CONTENTFUL_SPACE_ID }} \
            --management-token ${{ env.CONTENTFUL_TOKEN }} \
            --environment-id pr-${{ github.event.pull_request.number }} \
            --name "Preview for PR #${{ github.event.pull_request.number }}" \
            --source master
      - name: Run migrations in preview env
        run: |
          contentful space migration ./Migrations/index.js \
            --space-id ${{ env.CONTENTFUL_SPACE_ID }} \
            --environment-id pr-${{ github.event.pull_request.number }} \
            --management-token ${{ env.CONTENTFUL_TOKEN }}
      - name: Validate schema
        env:
          CONTENTFUL_TOKEN: ${{ env.CONTENTFUL_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ env.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENVIRONMENT_ID: pr-${{ github.event.pull_request.number }}
        run: node ./scripts/validateSchema.js
      - name: Cleanup preview environment
        if: always()
        run: |
          contentful environment delete \
            --space-id ${{ env.CONTENTFUL_SPACE_ID }} \
            --management-token ${{ env.CONTENTFUL_TOKEN }} \
            --environment-id pr-${{ github.event.pull_request.number }}

  # Production Promotion: Lock/Promote/Unlock
  promote-env:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Contentful CLI
        run: npm install -g contentful-cli
      - name: Lock master environment (simulate or real external script)
        run: |
          bash ./scripts/contentful-lock-master.sh \
            ${{ env.CONTENTFUL_SPACE_ID }} \
            ${{ env.CONTENTFUL_TOKEN }}
      - name: Upload roles backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: contentful-roles-backup
          path: roles-backup.json
          retention-days: 1
      - name: Promote testing -> production
        run: |
          contentful environment alias create \
            --space-id ${{ env.CONTENTFUL_SPACE_ID }} \
            --management-token ${{ env.CONTENTFUL_TOKEN }} \
            --alias-id master \
            --environment-id testing --force
      - name: Download roles backup artifact
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: contentful-roles-backup
          path: .
      - name: Unlock master environment
        if: always()
        run: |
          bash ./scripts/contentful-unlock-master.sh \
            ${{ env.CONTENTFUL_SPACE_ID }} \
            ${{ env.CONTENTFUL_TOKEN }}